// Pixel icons for gallery folders. Pure data so the server, the admin and the browser can all use it.
// The folder itself takes the site's accent colour, so it changes with the theme and the season.
// Symbols are 10x10: k outline, w white, y yellow, o orange, r red, p pink, v violet, b blue, c cyan, g green, s grey, d brown.

export const FOLDER_ICONS = ["folder", "bike", "night", "music", "camera", "mountain", "tree", "sun", "snow", "city", "star", "heart", "game", "cat", "car", "food"] as const;
export type FolderIcon = (typeof FOLDER_ICONS)[number];

export const ICON_LABEL: Record<FolderIcon, string> = {
  folder: "plain folder",
  bike: "motorcycle",
  night: "moon / night",
  music: "music / concert",
  camera: "camera",
  mountain: "mountains / outdoor",
  tree: "tree / nature",
  sun: "sun / summer",
  snow: "snow / winter",
  city: "city",
  star: "star / favourites",
  heart: "heart / people",
  game: "games",
  cat: "cat",
  car: "car / trip",
  food: "food",
};

export const ICON_PIX: Record<string, string> = {
  k: "#2c2230", w: "#fff8ef", y: "#ffd54a", o: "#f29a3a", r: "#e04b4b", p: "#ff8fb4", v: "#9c7cf0", b: "#6fb3ff", c: "#8fe3f0", g: "#5fc97a", s: "#a7adbd", d: "#9a6a3e", n: "#2b3b6c",
  // the folder: front, back, outline, all from the theme
  F: "var(--accent)",
  B: "color-mix(in srgb, var(--accent) 62%, #000)",
  H: "color-mix(in srgb, var(--accent) 55%, #fff)",
};

// 16x12 folder, closed and open
export const FOLDER_CLOSED = [
  "..kkkkk.........",
  ".kBBBBBk........",
  "kBBBBBBBkkkkkkk.",
  "kHHHHHHHHHHHHHHk",
  "kFFFFFFFFFFFFFFk",
  "kFFFFFFFFFFFFFFk",
  "kFFFFFFFFFFFFFFk",
  "kFFFFFFFFFFFFFFk",
  "kFFFFFFFFFFFFFFk",
  "kFFFFFFFFFFFFFFk",
  "kFFFFFFFFFFFFFFk",
  ".kkkkkkkkkkkkkk.",
];
export const FOLDER_OPEN = [
  "..kkkkk.........",
  ".kBBBBBk........",
  "kBBBBBBBkkkkkkk.",
  "kBBwwwwwwwwwwwBk",
  "kBkkkkkkkkkkkkkkk",
  "kBkHHHHHHHHHHHHHk",
  "kBkFFFFFFFFFFFFFk",
  "kkFFFFFFFFFFFFFk.",
  "kkFFFFFFFFFFFFFk.",
  "kFFFFFFFFFFFFFk..",
  "kFFFFFFFFFFFFFk..",
  ".kkkkkkkkkkkkk...",
];

export const SYMBOLS: Record<Exclude<FolderIcon, "folder">, string[]> = {
  bike: [
    "..........",
    "......kk..",
    ".....kwk..",
    "..kkkkkkk.",
    ".krrrrrkkk",
    "kkkrrkksk.",
    "kwk.kkkkk.",
    "kskk...kwk",
    "kwk....ksk",
    ".k......k.",
  ],
  night: [
    "...kkkk...",
    "..kyyyk...",
    ".kyyyk..w.",
    ".kyyk.....",
    "kyyyk...w.",
    "kyyyk.....",
    "kyyyyk....",
    ".kyyyykkk.",
    "..kyyyyyk.",
    "...kkkkk..",
  ],
  music: [
    "...kkkkkk.",
    "...kvvvvk.",
    "...kkkkkk.",
    "...k....k.",
    "...k....k.",
    "...k....k.",
    ".kkk..kkk.",
    "kvvvk.vvvk",
    "kvvvkkvvvk",
    ".kkk..kkk.",
  ],
  camera: [
    "..........",
    "..kkk.....",
    ".kssskkkk.",
    "kkkkkkkkkk",
    "ksskkkkrsk",
    "kskbbbkssk",
    "kskbwbkssk",
    "kskbbbkssk",
    "ksskkkkssk",
    "kkkkkkkkkk",
  ],
  mountain: [
    "..........",
    "....k.....",
    "...kwk....",
    "..kwwsk...",
    "..kssskk..",
    ".kssssksk.",
    ".ksssskssk",
    "kssssssssk",
    "kggggggggk",
    "kkkkkkkkkk",
  ],
  tree: [
    "....kk....",
    "...kggk...",
    "..kggggk..",
    ".kgggggk..",
    "..kggggk..",
    ".kggggggk.",
    "kggggggggk",
    "kkkkddkkkk",
    "....dd....",
    "...kddk...",
  ],
  sun: [
    "....y.....",
    ".y..y..y..",
    "..kkkkk...",
    "..kyyyk...",
    "yykyoykyy.",
    "..kyyyk...",
    "..kkkkk...",
    ".y..y..y..",
    "....y.....",
    "..........",
  ],
  snow: [
    "....c.....",
    "..c.c.c...",
    "...ccc....",
    "cccckcccc.",
    "...ccc....",
    "..c.c.c...",
    "....c.....",
    "..........",
    "..........",
    "..........",
  ],
  city: [
    "......kkk.",
    "..kkk.kyk.",
    "..kyk.ksk.",
    "kkksk.kyk.",
    "kykyk.ksk.",
    "kskskkkyk.",
    "kykykykskk",
    "kskskskyk.",
    "kykykykskk",
    "kkkkkkkkkk",
  ],
  star: [
    "....kk....",
    "....yk....",
    "...kyyk...",
    "kkkkyykkkk",
    "kyyyyyyyyk",
    ".kyyyyyyk.",
    "..kyyyyk..",
    ".kyykkyyk.",
    ".kyk..kyk.",
    ".kk....kk.",
  ],
  heart: [
    "..........",
    ".kk...kk..",
    "kppk.kppk.",
    "kpwppppppk",
    "kppppppppk",
    ".kppppppk.",
    "..kppppk..",
    "...kppk...",
    "....kk....",
    "..........",
  ],
  game: [
    "..........",
    "..........",
    ".kkkkkkkk.",
    "kvvvvvvvvk",
    "kvwvvvvpvk",
    "kwwwvvpvpk",
    "kvwvvvvpvk",
    "kvvvkkvvvk",
    ".kkk..kkk.",
    "..........",
  ],
  cat: [
    "..........",
    ".k.....k..",
    "kok...kok.",
    "kooooooook",
    "kokooookok",
    "kooowwoook",
    ".koooooook",
    ".kkkkkkkk.",
    "..........",
    "..........",
  ],
  car: [
    "..........",
    "..........",
    "...kkkkk..",
    "..kbbkbbk.",
    ".kbbbkbbbk",
    "kkkkkkkkkk",
    "krrrrrrrrk",
    "kkwkkkkwkk",
    ".kkk..kkk.",
    "..........",
  ],
  food: [
    "..........",
    "....k.k...",
    "...k.k....",
    "..........",
    "kkkkkkkkkk",
    "kwwwwwwwwk",
    "kwppwyywwk",
    ".kwwwwwwk.",
    "..kkkkkk..",
    "..........",
  ],
};
